language: python
python:
  - "3.8"
before_install:
  - pip3 install codecov
install:
  - pip3 install -r requirements.txt
script: python3 DeepNetworkTests.py || python DeepNetworkTests.py
after_success:
  - python3 -m codecov
