language: python
python:
  - "3.8"
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt
script: python3 DeepNetworkTests.py || python DeepNetworkTests.py
after_success:
  - codecov
