sudo: false
language: python
python:
  - "3.8"
install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
script:
  - python3 DeepNetworkTests.py
  - coverage run DeepNetworkTests.py

after_success:
  - bash <(curl https://codecov.io/bash)
